"""Core clauses per category (synthetic). Messages are composed as opener + core + tail + optional link.
Opener/tail pools are SHARED across scam and legitimate classes so they are not shortcuts for the model.
Splitting is done per core clause, so test cores are never seen in training."""

CORES = {
 "bank_kyc": [
  ("english", "your {bank} account KYC has expired and the account will be blocked"),
  ("english", "your {bank} account is on hold until PAN and Aadhaar are re-verified"),
  ("english", "failure to complete KYC will freeze your {bank} savings account"),
  ("english", "your {bank} debit card will be deactivated because KYC is pending"),
  ("english", "mandatory re-KYC for your {bank} net banking is required to avoid restrictions"),
  ("english", "your {bank} mobile banking access ends today unless you update your PAN card"),
  ("tamil_english", "ungal {bank} account KYC update illana block aagidum"),
 ],
 "upi_payment": [
  ("english", "you have a pending collect request of {amt}; approve it and enter your UPI PIN to receive money"),
  ("english", "scan the QR code below and enter your PIN to get your refund of {amt}"),
  ("english", "I sent {amt} to you by mistake, please accept the request on your UPI app and send the PIN"),
  ("english", "your cashback of {amt} is ready, accept the collect request to receive it"),
  ("english", "payment of {amt} is stuck; confirm with your UPI PIN to reverse the transaction"),
  ("english", "to receive {amt} in your wallet, authorise the payment request now"),
  ("tamil_english", "unga {amt} refund-ku UPI PIN anuppunga, collect request approve pannunga"),
 ],
 "job_internship": [
  ("english", "you are selected for a work from home job at {co}; pay a registration fee of {amt} to confirm"),
  ("english", "your internship offer from {co} is ready after you pay a refundable deposit of {amt}"),
  ("english", "earn {amt} daily by liking videos, no interview needed, joining fee applies"),
  ("english", "urgent hiring for data entry with high salary; send a security deposit of {amt} to start"),
  ("english", "your resume is shortlisted by {co}; pay the training kit charges of {amt} to receive the offer letter"),
  ("english", "part-time typing job, daily payment guaranteed, first pay a processing fee of {amt}"),
  ("tamil_english", "work from home velai kidaikum, registration kattanam {amt} anuppunga"),
 ],
 "investment": [
  ("english", "invest {amt} today and get guaranteed {n}0% returns within {n} days"),
  ("english", "our crypto scheme will double your money with zero risk"),
  ("english", "join our VIP stock tips group for sure-shot profits and guaranteed returns"),
  ("english", "our AI trading bot earns fixed daily income, 100% profit guaranteed"),
  ("english", "limited slots in our pre-launch fund offering risk-free monthly income"),
  ("english", "deposit {amt} into our forex platform and withdraw triple profit next week"),
  ("tamil_english", "{amt} invest pannunga, {n} naalil double panam guaranteed"),
 ],
 "prize_lottery": [
  ("english", "congratulations, you have won a lucky draw prize; pay {amt} to claim it"),
  ("english", "you are the lucky winner of a free smartphone; pay the delivery charge of {amt}"),
  ("english", "your number was selected in a lottery of Rs. 25,00,000; pay tax of {amt} to release the prize"),
  ("english", "you have won a gift voucher worth {amt}; confirm your card details to receive it"),
  ("english", "winner announcement: claim your cash reward by paying a small processing fee"),
  ("english", "your mobile number won the mega bumper draw, contact our agent to collect the prize"),
  ("tamil_english", "neenga lucky draw prize jeythirukkeenga, claim panna {amt} fee anuppunga"),
 ],
 "support_impersonation": [
  ("english", "this is {bank} customer care, we detected suspicious activity; install a remote access app so we can fix it"),
  ("english", "technical support here: your device has a virus; download the support tool and give us access"),
  ("english", "your order of {amt} will be charged; if this was not you call our helpline and share the OTP"),
  ("english", "your courier is on hold at the depot; pay a re-delivery fee of {amt} to avoid return"),
  ("english", "our support agent will refund {amt}; share the screen code so we can process it"),
  ("english", "your SIM will be blocked; contact our executive on the number given and confirm your details"),
  ("tamil_english", "naan {bank} customer care, unga account-la problem, remote app install pannunga"),
 ],
 "govt_impersonation": [
  ("english", "Income Tax Department: your refund of {amt} is approved; submit bank details to receive it"),
  ("english", "cyber police notice: a case is registered against your Aadhaar; pay a penalty or face arrest"),
  ("english", "customs has seized your parcel; pay a clearance fee of {amt} to avoid legal action"),
  ("english", "TRAI notice: your mobile number will be disconnected; verify your Aadhaar with our officer"),
  ("english", "traffic department: an unpaid challan of {amt} is pending; pay now to avoid court notice"),
  ("english", "your PAN is suspended by the government; update details immediately to avoid a fine"),
  ("tamil_english", "police notice: unga Aadhaar-la case irukku, {amt} penalty udane kattunga"),
 ],
 "account_verification": [
  ("english", "unusual sign-in detected on your account; verify your identity or it will be closed"),
  ("english", "your mailbox is full and will be deactivated unless you verify your account"),
  ("english", "your account has been temporarily limited; confirm your identity to restore access"),
  ("english", "we detected a policy violation on your page; verify within {n} hours or it will be disabled"),
  ("english", "your subscription account needs re-verification to avoid suspension"),
  ("english", "security check required: confirm your account ownership to continue using the service"),
  ("tamil_english", "ungal account verify pannunga illana {n} hours-la close aagidum"),
 ],
 "credential_theft": [
  ("english", "your password expires today; enter your current password to keep your account active"),
  ("english", "reply with your OTP and card number to secure your account"),
  ("english", "IT helpdesk: confirm your username and password to complete the mandatory security upgrade"),
  ("english", "your card is locked; share your CVV and OTP to unlock it"),
  ("english", "to avoid deactivation please send your net banking ID and password"),
  ("english", "provide your login credentials and the code sent to your phone for verification"),
  ("tamil_english", "ungal password matrum OTP udane anuppunga, account lock aagidum"),
 ],
 "phishing": [
  ("english", "please review the attached invoice and sign in to view the document"),
  ("english", "a shared file is waiting for you; open the link to view it"),
  ("english", "your package could not be delivered; reschedule your delivery using the link"),
  ("english", "your subscription payment was declined; update your billing information to avoid cancellation"),
  ("english", "you have a new voice message; sign in to listen to it"),
  ("english", "your document is ready for e-signature; log in with your email to open it"),
  ("tamil_english", "ungal parcel deliver aagala, inge click pannunga"),
 ],
 "legitimate": [
  ("english", "your OTP for the transaction is 482913 and is valid for 10 minutes; do not share it with anyone"),
  ("english", "{amt} was debited from your {bank} account ending 4521; if this was not you, call the number on your card"),
  ("english", "your order has been shipped and will arrive by Friday; you can track it in the app"),
  ("english", "the team meeting has moved to 3 PM tomorrow; please update your calendar"),
  ("english", "your electricity bill of {amt} is generated; pay it in the official app before the due date"),
  ("english", "your appointment is scheduled for Monday at 10 AM; call the clinic to reschedule"),
  ("english", "are we still on for dinner on Saturday; let me know what time works"),
  ("english", "thanks for attending the interview at {co}; results will be shared via the careers portal and no fees are charged at any stage"),
  ("english", "your statement is ready; never share your card details or OTP with anyone"),
  ("english", "assignment 3 is due on Friday; upload your submission on the college portal"),
  ("english", "your train ticket is confirmed for coach S4; carry a valid ID proof"),
  ("english", "your password was changed successfully; if this was not you, reset it from the official website"),
  ("english", "your offer letter from {co} is attached; sign and return it by Friday, no payment is required"),
  ("english", "your recharge of {amt} was successful and validity is extended by 28 days"),
  ("english", "your library book is due tomorrow; return it to avoid the late fee as per college rules"),
  ("english", "your cab is arriving in 3 minutes; share the trip code only with the driver"),
  ("english", "a new sign-in from Chennai was noticed; if it was you no action is needed"),
  ("english", "your fixed deposit matures on 15-Nov; visit your branch or the official app to renew"),
  ("english", "the project report must be submitted today by 5 PM; please send your part"),
  ("english", "your payment of {amt} to {co} was received; this is an automated receipt"),
  ("tamil_english", "naalaiku meeting 10 AM-ku irukku, time-ku vanga"),
  ("tamil_english", "unga order dispatch aagiduchu, naalaiku delivery varum"),
  ("tamil_english", "unga statement ready, official app-la login pannitu paarunga, OTP yaarukum share pannathinga"),
  ("tamil_english", "project submission naalaiku, unga part anuppunga please"),
 ],
}

OPENERS = ["", "", "Dear customer, ", "Hi {name}, ", "Alert: ", "Notice: ", "Hello, ", "Important: "]
TAILS = ["", "", "", " Thank you.", " Regards, Team.", " Act immediately.", " Please do it today.", " Reply if you need help."]
LINKS_SCAM = ["", "", " {url}", " Click here: {url}", " Visit {url}", " Tap the link: {url}"]
LINKS_LEGIT = ["", "", "", " Details: {ourl}", " Visit {ourl}"]
